mysite/animalSite/urls.py
from django.urls import path
from . import views

app_name='animal'
urlpatterns = [
    # path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('index/create/', views.created, name='created'),
    path('index/creating/', views.creating, name='creating'),
    path('<int:page_number>/detail/remov', views.remov, name='remov'),
    path('<int:page_number>/detail/editing', views.editing, name='editing'),
    path('<int:page_number>/detail/edit', views.edit_descript, name='edit'),
    path('<int:page_number>/detail/',views.detail, name='detail'),
    path('<int:page_number>/page/', views.page, name='page'),
    path('test_de/', views.test_delete, name='test_delete'),
    path('deleting/', views.deleting, name='deleting'),
    path('table/', views.table, name='table'),
    path('table/<int:animal_id>/show_table_descrip/', views.show_table_descrip, name='show_table_descrip'),
]
    # {% for name in latest_animal_name %}
    #     <li><a href="/animalSite/{{ Animal.id }}/">{{ name.animal_name }}</a></li>
    # {% endfor %}

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('animal/', include('animalSite.urls')),
    path('admin/', admin.site.urls),
]

mysite/animalSite/models.py
from django.db import models

class Animal(models.Model):
    animal_name = models.CharField(max_length=100)
    def __str__(self):
        return self.animal_name


class Description(models.Model):
    animal = models.OneToOneField(
        Animal,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    food = models.TextField()
    habitat = models.TextField()
    legs = models.IntegerField(default=4)

    def __str__(self):
        return self.food+" "+self.habitat+" "+str(self.legs)

mysite/animalSite/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse


from .models import Animal, Description

def table(request):
    animal_field = Animal._meta.fields
    animal_list = Animal.values_list().all()
    return render(request, 'table.html', {'animal_field':animal_field,"animal_list":animal_list})

def test_delete(request):
    list_animal_name=Animal.objects.order_by("animal_name")
    return render(request, 'radioDelete.html', {'list_animal_name': list_animal_name})

def deleting(request):
    Animal.objects.get(pk=request.POST['radio']).delete()
    return HttpResponseRedirect(reverse('animal:index'))

def index(request):
    list_animal_name=Animal.objects.order_by("animal_name")
    return render(request, 'index.html', {'list_animal_name': list_animal_name})

def remov(request,page_number):
    Animal.objects.get(pk=page_number).delete()
    return HttpResponseRedirect(reverse('animal:index'))

def created(request):
    return render(request, 'create.html')

def creating(request):
    add = Animal(animal_name=request.POST['input_name'])
    add.save()
    add_des = Description(animal=add,food=request.POST['input_food'],habitat=request.POST['input_habitat'],legs=request.POST['input_legs'])
    add_des.save()
    # return HttpResponseRedirect(reverse('animal:index'))
    return HttpResponseRedirect(reverse('animal:index'))

def page(request,page_number):
    template = loader.get_template("index.html")
    return HttpResponse(template.render())

def edit_descript(request,page_number):
    animal_num = Animal.objects.get(pk=page_number)
    return render(request, 'edit_descript.html', {'animal_num': animal_num})

def editing(request,page_number):
    animal_edit = get_object_or_404(Animal, pk=page_number)
    animal_edit.description.food=request.POST['input_food']
    animal_edit.description.habitat = request.POST['input_habitat']
    animal_edit.description.legs = request.POST['input_legs']
    animal_edit.description.save()
    return HttpResponseRedirect(reverse('animal:detail', args=(page_number,)))

def detail(request,page_number):
    latest_animal_name = get_object_or_404(Animal, pk=page_number)
    return render(request, 'detail.html', {'latest_animal_name': latest_animal_name})
# Create your views here.

def show_table_descrip(request,animal_id):
    

mysite/animalSite/templates/create.html
<form action="{% url 'animal:creating' %}" method="post">
{% csrf_token %}
<u><h1>Please fill data below.</h1></u>
<h2>Name : <input type="TextInput" name="input_name" value=""> </h2>
    <li>food    :  <input type="TextInput" name="input_food" value=""></li>
    <li>habitat :  <input type="TextInput" name="input_habitat" value=""></li>
    <li>legs    :  <input type="TextInput" name="input_legs" value=""></li>
<h1></h1>
<input type="submit" value="Submit">
<h1></h1>
</form>

<form action="{% url 'animal:index' %}" method="get">
<input type="submit" value="Cancel">
</form>

mysite/animalSite/templates/detail.html
<!DOCTYPE html>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>{{ latest_animal_name.animal_name }}</h1>
    <li>food : {{ latest_animal_name.description.food }}
    <li>habitat : {{ latest_animal_name.description.habitat }}
    <li>legs : {{ latest_animal_name.description.legs }}
<h1></h1>

<form action="{% url 'animal:edit' latest_animal_name.id%}" method="get">
<input type="submit" value="EDIT">
</form>
<h1></h1>

<form action="{% url 'animal:remov' latest_animal_name.id%}" method="post">
{% csrf_token %}
<input type="submit" value="DELETE">
</form>
<h1></h1>

<form action="{% url 'animal:index' %}" method="get">
<input type="submit" value="BACK">
</form>

mysite/animalSite/templates/edit_descript.html
<!DOCTYPE html>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'animal:editing' animal_num.id %}" method="post">
{% csrf_token %}
<u><h1>Select what do you want to edit.</h1></u>
<h2>Name : {{ animal_num.animal_name }}</h2>
    <li>food    :  <input type="TextInput"
        name="input_food" value="{{ animal_num.description.food }}"></li>
    <li>habitat :  <input type="TextInput"
        name="input_habitat" value="{{ animal_num.description.habitat }}"></li>
    <li>legs    :  <input type="TextInput"
        name="input_legs" value="{{ animal_num.description.legs }}"></li>
<h1></h1>
<input type="submit" value="sub">
<h1></h1>
</form>

<form action="{% url 'animal:detail' animal_num.id %}" method="get">
<input type="submit" value="Cancel">
</form>

mysite/animalSite/templates/index.html
<style>
* {
  box-sizing:border-box;
}

.left {
  /* background-color:#2196F3; */
  padding:20px;
  float:left;
  width:10%; /* The width is 20%, by default */
}

.main {
  /* background-color:#f1f1f1; */
  padding:20px;
  float:left;
  width:10%; /* The width is 60%, by default */
}

.right {
    /* background-color:#4CAF50; */
  padding:20px;
  float:left;
  width:10%; /* The width is 20%, by default */
}

/* Use a media query to add a break point at 800px: */
@media screen and (max-width:800px) {
  .left, .main, .right {
    width:100%; /* The width is 100%, when the viewport is 800px or smaller */
  }
}
</style>
{% if list_animal_name %}
<h1>List of Animals </h1>
    <ul>
    {% for name in list_animal_name %}
        <li><a href="{% url 'animal:detail' name.id %}">{{ name.animal_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Data are available.</p>
{% endif %}

<form action="{% url 'animal:created' %}" method="get">
<div class="left">
  <input type="submit" value="Add_more">
</div>
</form>

<form action="{% url 'animal:test_delete' %}" method="get">
<div class="main">
  <input type="submit" value="Delete">
</div>
</form>

<form action="{% url 'animal:table' %}" method="get">
<div class="right">
  <input type="submit" value="Table">
</div>
</form>

mysite/animalSite/templates/radioDelete.html
<form action="{% url 'animal:deleting' %}" method="post">
{% csrf_token %}
{% if list_animal_name %}
<h1>List of Animals </h1>
    <ul>
    {% for name in list_animal_name %}
        <input type="radio" name='radio' value={{ name.id }} > <a href="{% url 'animal:detail' name.id %}">{{ name.animal_name }}</a>
    {% endfor %}
    </ul>
{% else %}
    <p>No Data are available.</p>
{% endif %}
<input type="submit" value="submit">
</form>
<form action="{% url 'animal:index' %}" method="get">
<input type="submit" value="cancel">
</form>

mysite/animalSite/templates/table.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>

<body>

<table border="1">
    <tr>
        {% for field in animal_field%}
            <th>{{field.name}}</th>
        {% endfor%}
    </tr>
    {% for ani in animal_list%}
    <div style="overflow-x:auto;"></div>
    <tr>
        {% for attr in ani%}
            {% if forloop.counter0 == 1 %}
                <td><a href="{% url 'animal:show_table_descrip' qst.0 %}">{{attr}}</a></td>
            {% else %}
                <td>{{attr}}</td>
            {% endif %}
        {% endfor%}
    </tr>
    </div>
    {% endfor%}

</table>

</body>

mysite/animalSite/templates/test.html
<form action="{% url 'animal:testing_a' %}" method="post">
{% csrf_token %}
<u><h1>Please fill data below.</h1></u>
<h2>Name : <input type="TextInput" name="input_name" value=""> </h2>
    <li>food    :  <input type="checkbox" name="check" value="1"></li>
    <li>habitat :  <input type="checkbox" name="check" value="2"></li>
    <li>legs    :  <input type="checkbox" name="check"></li>
    <input type="color" name="col" value='col'>
    <input type="file" name="fil" >
    <input type="image" name="ima" value='ima'>
<h1></h1>
<input type="submit" value="Submit">
<h1></h1>
</form>